server {
  server_name tdu-src.com;
  access_log /home/sofuken/public_html/tdu-src.com/log/access.log;
  error_log /home/sofuken/public_html/tdu-src.com/log/error.log;

  root /home/sofuken/public_html/tdu-src.com/public;
  index index.html;

  location / {
    try_files $uri $uri/ $uri.html =404;
  }

  location /project/sofchara-fest-stamp-rally-2024 {
    proxy_pass http://unix:/home/sofuken/tdu-src.com-project/sofchara-fest-stamp-rally-2024/sofchara-fest-stamp-rally-2024.sock;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /project/sofchara-fest-stamp-rally-2025 {
    proxy_pass http://unix:/home/sofuken/tdu-src.com-project/sofchara-fest-stamp-rally-2025/sofchara-fest-stamp-rally-2025.sock;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /static {
    alias /usr/share/nginx/html/tdu-src.com-project/sofchara-fest-stamp-rally-2025/static;
  }

  location /media {
    alias /home/sofuken/tdu-src.com-project/sofchara-fest-stamp-rally-2025/sofchara-fest-stamp-rally-2025/project/media;
  }

  location ~ .*/\..* {
    deny all;
  }

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/tdu-src.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/tdu-src.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
  if ($host = tdu-src.com) {
    return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80;
  server_name tdu-src.com;
  return 404; # managed by Certbot
}
